# chap 7 naive bayse classifier
- question is designed to practise coding
    + naive bayse classifier with laplas correcting factor

In [17]:
import numpy as np
X = np.random.random((20,2))
X.shape



(20, 2)

In [18]:
mut = np.array([2,6])
y = np.eye(2)*mut

In [19]:
print(mut*X)
print(X.dot(y))

[[1.9814806  5.98184291]
 [0.61747189 3.94589884]
 [1.82937415 5.29831625]
 [1.06261404 2.04404486]
 [1.63714339 0.76233913]
 [1.82966033 1.08113592]
 [0.70507598 3.88642984]
 [0.5454288  3.81638899]
 [0.46144826 2.4036525 ]
 [0.28569412 1.28298782]
 [0.66206707 1.68063271]
 [1.30656644 3.50116288]
 [1.3902279  3.74124211]
 [1.95818806 5.79598845]
 [1.67146319 1.24175783]
 [1.66879706 2.92552398]
 [0.527914   0.83128581]
 [0.03020404 1.73887015]
 [0.78603866 0.1127478 ]
 [0.77953367 4.72727383]]
[[1.9814806  5.98184291]
 [0.61747189 3.94589884]
 [1.82937415 5.29831625]
 [1.06261404 2.04404486]
 [1.63714339 0.76233913]
 [1.82966033 1.08113592]
 [0.70507598 3.88642984]
 [0.5454288  3.81638899]
 [0.46144826 2.4036525 ]
 [0.28569412 1.28298782]
 [0.66206707 1.68063271]
 [1.30656644 3.50116288]
 [1.3902279  3.74124211]
 [1.95818806 5.79598845]
 [1.67146319 1.24175783]
 [1.66879706 2.92552398]
 [0.527914   0.83128581]
 [0.03020404 1.73887015]
 [0.78603866 0.1127478 ]
 [0.77953367 4.72727383]

In [20]:
np.equal(mut*X,X.dot(y))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

**generate data**

In [41]:
data = pd.DataFrame(np.random.randint(3,size = (2,10)))
def dic4map(x):
    dict1 = dict(zip(range(10),['smooth','rough','semi-smooth']))
    return pd.Series.apply(x,lambda x:dict1[x])

In [42]:
data.iloc[0,:] = dic4map(data.iloc[0,:]) 

In [43]:
data

0      1      2      3       4       5      6      7       8  \
0  semi-smooth  rough  rough  rough  smooth  smooth  rough  rough  smooth   
1            1      2      0      0       1       1      0      1       0   

        9  
0  smooth  
1       2

1 ROUGE-1 Average_R: 0.51416 (95%-conf.int. 0.50883 - 0.51942)

1 ROUGE-1 Average_P: 0.37139 (95%-conf.int. 0.36689 - 0.37612)

1 ROUGE-1 Average_F: 0.41681 (95%-conf.int. 0.41263 - 0.42101)

![ROUGE-l](https://img-blog.csdn.net/20171202143111808?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvcXFfMjUyMjIzNjE=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

In [46]:
import numpy as np
P = 0.37139 
R = 0.51416
F = 0.41681
def cal(P,R,F):
    BETA_SQUARE = (P*R - F*R)/(F*P - P*R)
    return np.sqrt(BETA_SQUARE)
cal(P,R,F)

0.8036919670751749

1 ROUGE-2 Average_R: 0.23153 (95%-conf.int. 0.22641 - 0.23660)

1 ROUGE-2 Average_P: 0.16708 (95%-conf.int. 0.16272 - 0.17134)

1 ROUGE-2 Average_F: 0.18727 (95%-conf.int. 0.18299 - 0.19157)



In [47]:
cal(0.16708,0.23153,0.18727)

0.7950672365859885